# Generated by Django 5.1 on 2024-09-13 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('creditos', models.IntegerField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_dictadas', to='universidad.persona')),
            ],
        ),
    ]
