# Generated by Django 5.1 on 2024-10-18 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('universidad', '0003_materia_inscripcion_persona_tipo'),
    ]

    def insertData(self, schema_editor):

        User = self.get_model('auth', 'User')

        admin_user = User.objects.get(username='admin')
        if admin_user is None:
            admin_user = User.objects.create_user('admin', 'admin@admin.com', 'admin!123')
            admin_user.is_superuser = True
            admin_user.is_staff = True
            admin_user.save()



    operations = [
        migrations.RunPython(insertData, atomic=True),
    ]
