# Generated by Django 5.1 on 2024-10-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0005_add_permissions_2'),
    ]
    def insertData(self, schema_editor):
        User = self.get_model('auth', 'User')
        Group = self.get_model('auth', 'Group')
        Permission = self.get_model('auth', 'Permission')

        admin_user = User.objects.get(username='admin')

        admin_group = Group.objects.get(name='Administrators')
        student_group = Group.objects.get(name='Students')
        teacher_group = Group.objects.get(name='Teachers')

        persona_view = Permission.objects.get(codename='view_persona')
        persona_add = Permission.objects.get(codename='add_persona')
        persona_update = Permission.objects.get(codename='change_persona')
        persona_delete = Permission.objects.get(codename='delete_persona')

        materia_view = Permission.objects.get(codename='view_materia')
        materia_add = Permission.objects.get(codename='add_materia')
        materia_update = Permission.objects.get(codename='change_materia')
        materia_delete = Permission.objects.get(codename='delete_materia')

        user_view = Permission.objects.get(codename='view_user')
        user_add = Permission.objects.get(codename='add_user')
        user_update = Permission.objects.get(codename='change_user')
        user_delete = Permission.objects.get(codename='delete_user')

        admin_group.permissions.set([
            persona_view, persona_add, persona_update, persona_delete,
            materia_view, materia_add, materia_update, materia_delete,
            user_view, user_add, user_update, user_delete
        ])
        student_group.permissions.set([
            persona_view, materia_view, user_view, user_update
        ])
        teacher_group.permissions.set([
            persona_view, materia_view, user_view, user_update, materia_update
        ])

        admin_user.groups.add(admin_group)

    operations = [
        migrations.RunPython(insertData, atomic=True),
    ]
