# Generated by Django 5.1 on 2024-09-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='personas'),
        ),
    ]
