# Generated by Django 5.1 on 2024-09-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_persona_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/personas'),
        ),
    ]
