# Generated by Django 5.1 on 2024-09-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_alter_persona_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='static/mascotas'),
        ),
    ]
